name: classification
time_limit_sec: 36000
data_name: dog-vs-cat
data_path: /data/AutoML_compete/dog-vs-cat/train
output_path: /home/yiran.wu/work_dirs/autodl_benchmark/dog-vs-cat
device_limit: 2
device_type: nvidia
