
Ë
root"_tf_keras_network*©{"class_name": "Functional", "name": "model", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "config": {"name": "model", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": {"class_name": "__tuple__", "items": [null]}, "dtype": "string", "sparse": false, "ragged": false, "name": "sentences"}, "name": "sentences", "inbound_nodes": []}, {"class_name": "BertTokenizer", "config": {"layer was saved without config": true}, "name": "bert_tokenizer", "inbound_nodes": [[["sentences", 0, 0, {}]]]}, {"class_name": "BertPackInputs", "config": {"name": "bert_pack_inputs", "trainable": true, "dtype": "float32", "seq_length": 128, "start_of_sequence_id": 101, "end_of_segment_id": 102, "padding_id": 0, "truncator": "round_robin"}, "name": "bert_pack_inputs", "inbound_nodes": [[["bert_tokenizer", 0, 0, {}]]]}, {"class_name": "Functional", "config": {"name": "model_1", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": {"class_name": "__tuple__", "items": [null]}, "dtype": "string", "sparse": false, "ragged": false, "name": "sentences"}, "name": "sentences", "inbound_nodes": []}, {"class_name": "BertTokenizer", "config": {"layer was saved without config": true}, "name": "bert_tokenizer", "inbound_nodes": [[["sentences", 0, 0, {}]]]}], "input_layers": [["sentences", 0, 0]], "output_layers": [["bert_tokenizer", 0, 0]]}, "name": "model_1", "inbound_nodes": []}], "input_layers": [["sentences", 0, 0]], "output_layers": {"input_word_ids": ["bert_pack_inputs", 0, 2], "input_mask": ["bert_pack_inputs", 0, 0], "input_type_ids": ["bert_pack_inputs", 0, 1]}}, "input_spec": [{"class_name": "InputSpec", "config": {"dtype": null, "shape": {"class_name": "__tuple__", "items": [null]}, "ndim": 1, "max_ndim": null, "min_ndim": null, "axes": {}}}], "build_input_shape": {"class_name": "TensorShape", "items": [null]}, "is_graph_network": true, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null]}, "string", "sentences"]}, "keras_version": "2.5.0", "backend": "tensorflow", "model_config": {"class_name": "Functional"}}
ò
root.layer-0"_tf_keras_input_layer*Â{"class_name": "InputLayer", "name": "sentences", "dtype": "string", "sparse": false, "ragged": false, "batch_input_shape": {"class_name": "__tuple__", "items": [null]}, "config": {"batch_input_shape": {"class_name": "__tuple__", "items": [null]}, "dtype": "string", "sparse": false, "ragged": false, "name": "sentences"}}
®
root.layer-1"_tf_keras_layer*„{"class_name": "BertTokenizer", "name": "bert_tokenizer", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "config": {"layer was saved without config": true}}
Ã
root.layer-2"_tf_keras_layer*™{"class_name": "BertPackInputs", "name": "bert_pack_inputs", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "config": {"name": "bert_pack_inputs", "trainable": true, "dtype": "float32", "seq_length": 128, "start_of_sequence_id": 101, "end_of_segment_id": 102, "padding_id": 0, "truncator": "round_robin"}}
ó	
root.layer-3"_tf_keras_network*Ç	{"class_name": "Functional", "name": "model_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "config": {"name": "model_1", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": {"class_name": "__tuple__", "items": [null]}, "dtype": "string", "sparse": false, "ragged": false, "name": "sentences"}, "name": "sentences", "inbound_nodes": []}, {"class_name": "BertTokenizer", "config": {"layer was saved without config": true}, "name": "bert_tokenizer", "inbound_nodes": [[["sentences", 0, 0, {}]]]}], "input_layers": [["sentences", 0, 0]], "output_layers": [["bert_tokenizer", 0, 0]]}, "input_spec": [{"class_name": "InputSpec", "config": {"dtype": null, "shape": {"class_name": "__tuple__", "items": [null]}, "ndim": 1, "max_ndim": null, "min_ndim": null, "axes": {}}}], "build_input_shape": {"class_name": "TensorShape", "items": [null]}, "is_graph_network": true, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null]}, "string", "sentences"]}, "keras_version": "2.5.0", "backend": "tensorflow", "model_config": {"class_name": "Functional"}}